[workspace]
members = [
    "utils",
    "archaeologist",
    "solitude",
    "soyuz",
    "corbynball",
    "cylons",
    "vermin",
    "taipan",
    "upto11",
    "gatchi",
    "vexation",
    "jackpot",
    "allhands"
]
